-- AlterTable: Add ERP-level fields to MrpRun
ALTER TABLE "MrpRun" ADD COLUMN IF NOT EXISTS "planningHorizonDays" INTEGER NOT NULL DEFAULT 90,
ADD COLUMN IF NOT EXISTS "periodStart" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "periodEnd" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "planType" TEXT NOT NULL DEFAULT 'STANDARD',
ADD COLUMN IF NOT EXISTS "includeSalesOrder" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "includeForecast" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "includeMinStock" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);

-- AlterTable: Add ERP-level fields to MrpSuggestion
ALTER TABLE "MrpSuggestion" ADD COLUMN IF NOT EXISTS "uomCode" TEXT,
ADD COLUMN IF NOT EXISTS "unitCost" DECIMAL(18,4),
ADD COLUMN IF NOT EXISTS "totalCost" DECIMAL(18,4),
ADD COLUMN IF NOT EXISTS "workCenter" TEXT,
ADD COLUMN IF NOT EXISTS "priority" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS "suggestedDate" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "leadTimeDays" INTEGER,
ADD COLUMN IF NOT EXISTS "bomId" TEXT,
ADD COLUMN IF NOT EXISTS "workOrderId" TEXT,
ADD COLUMN IF NOT EXISTS "notes" TEXT,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3);
