export type AppMenuItem = {
  title: string;
  path?: string;
  icon?: string | null;
  children?: AppMenuItem[];
};

export const appMenu: AppMenuItem[] = [
  { title: 'Dashboard & Analytics', icon: 'pi pi-chart-bar', path: '/' },
  {
    title: 'Core & Master Data',
    icon: 'pi pi-database',
    children: [
      {
        title: 'Master Perusahaan',
        icon: 'pi pi-building',
        children: [
          { title: 'Company Profile', path: '/core/company-profile', icon: null },
          { title: 'Branch/Location Management', path: '/core/branch-management', icon: null },
          { title: 'Currency & Exchange Rates', path: '/core/currency-rates', icon: null },
          { title: 'Unit of Measure (UOM)', path: '/core/unit-of-measure', icon: null },
          { title: 'Calendar & Fiscal Year', path: '/core/fiscal-year', icon: null },
        ],
      },
      {
        title: 'Keuangan Dasar',
        icon: 'pi pi-wallet',
        children: [
          { title: 'Chart of Accounts (COA)', path: '/core/chart-of-accounts', icon: null },
          { title: 'Cost Center & Profit Center', path: '/core/cost-center', icon: null },
          { title: 'Tax Configuration', path: '/core/tax-config', icon: null },
        ],
      },
      {
        title: 'User & Security',
        icon: 'pi pi-shield',
        children: [
          { title: 'User Management', path: '/core/user-management', icon: null },
          { title: 'Role & Permission', path: '/core/role-permission', icon: null },
          { title: 'Workflow Designer', path: '/core/workflow-designer', icon: null },
          { title: 'Approval Inbox', path: '/core/approval-inbox', icon: null },
          { title: 'Notification Preferences', path: '/core/notification-preferences', icon: null },
          { title: 'Audit Trail', path: '/core/audit-trail', icon: null },
        ],
      },
    ],
  },
  {
    title: 'CRM',
    icon: 'pi pi-users',
    children: [
      { title: 'CRM Dashboard', path: '/crm/dashboard', icon: null },
      { title: 'My Work', path: '/crm/my-work', icon: null },
      { title: 'CRM Pipeline', path: '/crm/pipeline', icon: null },
      { title: 'Lead Management', path: '/crm/lead-management', icon: null },
      { title: 'Opportunity Management', path: '/crm/opportunity-management', icon: null },
      { title: 'Customer Management', path: '/crm/customer-management', icon: null },
      { title: 'Customer Portal & B2B Portal', path: '/crm/customer-portal', icon: null },
      { title: 'Sales Activity', path: '/crm/sales-activity', icon: null },
      { title: 'Marketing Campaign', path: '/crm/marketing-campaign', icon: null },
      { title: 'Customer Service', path: '/crm/customer-service', icon: null },
    ],
  },
  {
    title: 'E-Commerce & Omnichannel',
    icon: 'pi pi-globe',
    children: [
      { title: 'Marketplace Integration', path: '/ecommerce/marketplace', icon: null },
      { title: 'Webstore Management', path: '/ecommerce/webstore', icon: null },
      { title: 'Omnichannel Order Aggregator', path: '/ecommerce/orders', icon: null },
      { title: 'Real-time Stock Synchronization', path: '/ecommerce/stock-sync', icon: null },
    ],
  },
  {
    title: 'Retail & POS (Advanced)',
    icon: 'pi pi-shop',
    children: [
      { title: 'POS Terminal (Omnichannel)', path: '/support/pos', icon: null },
      { title: 'Shift Management', path: '/pos/shift', icon: null },
      { title: 'Split Payment Processing', path: '/pos/split-payment', icon: null },
      { title: 'Loyalty & Rewards Management', path: '/pos/loyalty-rewards', icon: null },
      { title: 'Fiscal Printer Integration', path: '/pos/fiscal', icon: null },
    ],
  },
  {
    title: 'Sales & Distribution',
    icon: 'pi pi-shopping-cart',
    children: [
      { title: 'Sales Quotation', path: '/sales/quotation', icon: null },
      { title: 'Sales Order', path: '/sales/order', icon: null },
      { title: 'Delivery Order (DO)', path: '/sales/delivery-order', icon: null },
      { title: 'Pricing Management', path: '/sales/pricing', icon: null },
      { title: 'Subscription & Recurring Billing', path: '/sales/subscription', icon: null },
      { title: 'Sales Invoice', path: '/sales/invoice', icon: null },
      { title: 'Sales Return', path: '/sales/return', icon: null },
      { title: 'Sales Commission', path: '/sales/commission', icon: null },
      { title: 'Shipping Integration', path: '/sales/shipping', icon: null },
    ],
  },
  {
    title: 'Procurement (Purchasing)',
    icon: 'pi pi-shopping-bag',
    children: [
      { title: 'Purchase Requisition (PR)', path: '/procurement/requisition', icon: null },
      { title: 'Request for Quotation (RFQ)', path: '/procurement/rfq', icon: null },
      { title: 'Purchase Order (PO)', path: '/procurement/purchase-order', icon: null },
      { title: '3-Way Match (PO/GRN/Invoice)', path: '/procurement/three-way-match', icon: null },
      { title: 'Supplier Management', path: '/procurement/supplier', icon: null },
      { title: 'Vendor / Supplier Portal', path: '/procurement/vendor-portal', icon: null },
      { title: 'Purchase Invoice', path: '/procurement/invoice', icon: null },
      { title: 'Landed Cost Voucher', path: '/procurement/landed-cost', icon: null },
      { title: 'Purchase Return', path: '/procurement/return', icon: null },
    ],
  },
  {
    title: 'Inventory & Warehouse (WMS)',
    icon: 'pi pi-box',
    children: [
      { title: 'Item Master', path: '/inventory/item-master', icon: null },
      { title: 'Stock Management', path: '/inventory/stock', icon: null },
      { title: 'Goods Receipt Note (GRN)', path: '/inventory/goods-receipt', icon: null },
      { title: 'Putaway', path: '/inventory/putaway', icon: null },
      { title: 'Picking', path: '/inventory/picking', icon: null },
      { title: 'Packing', path: '/inventory/packing', icon: null },
      { title: 'Transfer (In-Transit)', path: '/inventory/transfer', icon: null },
      { title: 'Quality Inspection on Receipt', path: '/inventory/qc', icon: null },
      { title: 'Inventory Valuation', path: '/inventory/valuation', icon: null },
      { title: 'Batch & Serial Number', path: '/inventory/batch-serial', icon: null },
      { title: 'Multi-Location Inventory', path: '/inventory/multi-location', icon: null },
      { title: 'Inventory Planning', path: '/inventory/planning', icon: null },
      { title: 'Demand Planning & Forecast (AI)', path: '/inventory/ai-forecasting', icon: null },
      { title: 'Stock Opname', path: '/inventory/stock-opname', icon: null },
    ],
  },
  {
    title: 'Quality Management System (QMS)',
    icon: 'pi pi-verified',
    children: [
      { title: 'Non-Conformance Report (NCR)', path: '/qms/ncr', icon: null },
      { title: 'CAPA Management', path: '/qms/capa', icon: null },
      { title: 'Supplier Quality Rating', path: '/qms/supplier-rating', icon: null },
      { title: 'SOP & ISO Document Control', path: '/qms/sop-iso', icon: null },
      { title: 'Calibration Management', path: '/qms/calibration', icon: null },
    ],
  },
  {
    title: 'Manufacturing & Production',
    icon: 'pi pi-cog',
    children: [
      { title: 'Bill of Materials (BOM)', path: '/manufacturing/bom', icon: null },
      { title: 'Production Planning (MPS & MRP)', path: '/manufacturing/planning', icon: null },
      { title: 'Work Order (WO)', path: '/manufacturing/work-order', icon: null },
      { title: 'Production Execution', path: '/manufacturing/execution', icon: null },
      { title: 'Shop Floor Control', path: '/manufacturing/shop-floor', icon: null },
      { title: 'Maintenance (TPM)', path: '/manufacturing/maintenance', icon: null },
      { title: 'Production Costing', path: '/manufacturing/costing', icon: null },
    ],
  },
  {
    title: 'Field Service Management',
    icon: 'pi pi-map-marker',
    children: [
      { title: 'Technician Scheduling', path: '/fsm/scheduling', icon: null },
      { title: 'GPS Work Order', path: '/fsm/work-order', icon: null },
      { title: 'Field Spare Parts Consumption', path: '/fsm/spare-parts', icon: null },
      { title: 'Digital Signature & Handover', path: '/fsm/handover', icon: null },
    ],
  },
  {
    title: 'Rental & Asset Leasing',
    icon: 'pi pi-key',
    children: [
      { title: 'Rental Contracts', path: '/rental/contracts', icon: null },
      { title: 'Periodic Billing', path: '/rental/billing', icon: null },
      { title: 'Scheduled Maintenance', path: '/rental/maintenance', icon: null },
      { title: 'Usage-based Depreciation', path: '/rental/depreciation', icon: null },
    ],
  },
  {
    title: 'Finance & Accounting',
    icon: 'pi pi-dollar',
    children: [
      { title: 'Finance Dashboard', path: '/finance/dashboard', icon: null },
      {
        title: 'General Ledger',
        icon: null,
        children: [
          { title: 'Journal Entry', path: '/finance/journal', icon: null },
          { title: 'Cost Center Allocation', path: '/finance/cost-center-allocation', icon: null },
          { title: 'Inter-Company & Konsolidasi', path: '/finance/inter-company', icon: null },
        ],
      },
      {
        title: 'Cash & Bank',
        icon: null,
        children: [
          { title: 'Bank Reconciliation', path: '/finance/bank-reconciliation', icon: null },
          { title: 'Petty Cash & Fund Transfer', path: '/finance/petty-cash', icon: null },
          { title: 'Customer Receipt & Allocation', path: '/finance/customer-receipt', icon: null },
          { title: 'Vendor Payment & Allocation', path: '/finance/vendor-payment', icon: null },
          { title: 'Payment Request & Approval', path: '/finance/payment-request', icon: null },
        ],
      },
      {
        title: 'AR & AP',
        icon: null,
        children: [
          { title: 'Aging Report', path: '/finance/reports?tab=ag', icon: null },
          { title: 'Debt Collection (Intelligence)', path: '/finance/debt-collection', icon: null },
          { title: 'Vendor Reconciliation (3-Way)', path: '/finance/vendor-reconciliation', icon: null },
        ],
      },
      {
        title: 'Fixed Assets',
        icon: null,
        children: [
          { title: 'Asset Registration', path: '/finance/assets', icon: null },
          { title: 'Depreciation', path: '/finance/depreciation', icon: null },
          { title: 'Asset Revaluation & Disposal', path: '/finance/asset-disposal', icon: null },
        ],
      },
      { title: 'Budgeting & Budget Control', path: '/finance/budget', icon: null },
      { title: 'Period Closing', path: '/finance/closing', icon: null },
      { title: 'Financial Reporting', path: '/finance/reports?tab=pl', icon: null },
      {
        title: 'Settings',
        icon: null,
        children: [
          { title: 'Chart of Accounts', path: '/finance/coa', icon: null },
          { title: 'Cost Center', path: '/finance/cost-center', icon: null },
          { title: 'Profit Center', path: '/finance/profit-center', icon: null },
          { title: 'Fiscal Year', path: '/finance/fiscal', icon: null },
          { title: 'Tax Code', path: '/finance/tax-code', icon: null },
          { title: 'Bank Account', path: '/finance/bank', icon: null },
          { title: 'Cash Account', path: '/finance/cash', icon: null },
        ],
      },
    ],
  },
  {
    title: 'Indonesia Tax Management',
    icon: 'pi pi-receipt',
    children: [
      {
        title: 'PPN (Value Added Tax)',
        icon: null,
        children: [
          { title: 'Faktur Pajak Keluaran', path: '/tax/faktur-keluaran', icon: null },
          { title: 'Faktur Pajak Masukan', path: '/tax/faktur-masukan', icon: null },
          { title: 'NSFP Management', path: '/tax/nsfp', icon: null },
          { title: 'PPN Masa Summary', path: '/tax/ppn-masa', icon: null },
        ],
      },
      {
        title: 'PPh (Withholding Tax)',
        icon: null,
        children: [
          { title: 'e-Bupot Unifikasi', path: '/tax/e-bupot', icon: null },
          { title: 'PPh 21 Payroll Integration', path: '/tax/pph21', icon: null },
          { title: 'Bukti Potong 1721-A1', path: '/tax/bukti-potong', icon: null },
          { title: 'ID Billing Generator', path: '/tax/id-billing', icon: null },
        ],
      },
      {
        title: 'Compliance',
        icon: null,
        children: [
          { title: 'Tax Equalization', path: '/tax/equalization', icon: null },
          { title: 'Fiscal Reconciliation', path: '/tax/fiscal-reconciliation', icon: null },
        ],
      },
    ],
  },
  {
    title: 'HRIS & Productivity',
    icon: 'pi pi-id-card',
    children: [
      { title: 'Employee Database', path: '/hris/employee', icon: null },
      { title: 'Organization Structure', path: '/hris/org-structure', icon: null },
      { title: 'Recruitment (ATS)', path: '/hris/recruitment', icon: null },
      { title: 'Learning Management System (LMS)', path: '/hris/lms', icon: null },
      { title: 'Attendance', path: '/hris/attendance', icon: null },
      { title: 'Leave & Time Off', path: '/hris/leave', icon: null },
      { title: 'Overtime', path: '/hris/overtime', icon: null },
      { title: 'Shift Management', path: '/hris/shift', icon: null },
      { title: 'Payroll', path: '/hris/payroll', icon: null },
      { title: 'Employee Loans', path: '/hris/loans', icon: null },
      { title: 'Employee Self-Service (ESS)', path: '/hris/ess', icon: null },
      { title: 'KPI & Performance Review', path: '/hris/kpi', icon: null },
      { title: 'Expense Claims', path: '/hris/expense', icon: null },
      { title: 'Movements & Disciplinary', path: '/hris/movements', icon: null },
      { title: 'Timesheets & Productivity', path: '/hris/timesheets', icon: null },
      { title: 'Offboarding & Severance', path: '/hris/offboarding', icon: null },
      { title: 'HR Analytics Dashboard', path: '/hris/analytics', icon: null },
      { title: 'Succession Planning', path: '/hris/succession', icon: null },
    ],
  },
  {
    title: 'Logistics & Supply Chain',
    icon: 'pi pi-truck',
    children: [
      { title: 'Logistics Dashboard', path: '/logistics/dashboard', icon: null },
      { title: 'Fleet Management', path: '/logistics/fleet', icon: null },
      { title: 'Fleet Maintenance', path: '/logistics/maintenance', icon: null },
      { title: 'Driver Management', path: '/logistics/drivers', icon: null },
      { title: 'Trip & Manifest', path: '/logistics/trips', icon: null },
      { title: 'Delivery Order & POD', path: '/logistics/delivery', icon: null },
      { title: 'Route Optimization', path: '/logistics/route', icon: null },
      { title: '3PL & Partners', path: '/logistics/partners', icon: null },
      { title: 'Warehouse Operations', path: '/logistics/warehouse', icon: null },
      { title: 'Staging & Cross-dock', path: '/logistics/staging', icon: null },
      { title: 'Packing & Kitting', path: '/logistics/packing', icon: null },
    ],
  },
  {
    title: 'Project Management',
    icon: 'pi pi-folder-open',
    children: [
      { title: 'Project Master (Setup)', path: '/project/setup', icon: null },
      { title: 'Project Health Dashboard', path: '/project/dashboard', icon: null },
      { title: 'Gantt Planner', path: '/project/gantt', icon: null },
      { title: 'Issue & Risk Tracker', path: '/project/risks', icon: null },
      { title: 'Change Orders (CO)', path: '/project/change-orders', icon: null },
      { title: 'Master Project Sites', path: '/project/sites', icon: null },
      { title: 'Master Budget', path: '/project/budget', icon: null },
      { title: 'Tender & Contract Management', path: '/project/tender', icon: null },
      { title: 'Progress Billing', path: '/project/billing', icon: null },
      { title: 'Cost Control', path: '/project/cost-control', icon: null },
    ],
  },
  {
    title: 'Construction Management',
    icon: 'pi pi-building',
    children: [
      { title: 'S-Curve & Progress Tracking', path: '/project/progress-tracking', icon: null },
      { title: 'Site Management', path: '/construction/site', icon: null },
      { title: 'Material Request (MR)', path: '/construction/material-request', icon: null },
      { title: 'Subcontractor Management', path: '/construction/subcontractor', icon: null },
      { title: 'Daily Progress Report', path: '/construction/daily-progress', icon: null },
      { title: 'Drawing & Document Control', path: '/construction/drawing', icon: null },
      { title: 'Safety & HSE Checklist', path: '/construction/hse', icon: null },
      { title: 'Punch List (Defects)', path: '/construction/punch-list', icon: null },
      { title: 'Request for Inspection (RFI)', path: '/construction/rfi', icon: null },
      { title: 'Heavy Equipment Logs', path: '/construction/equipment', icon: null },
      { title: 'Weather & Impact Logs', path: '/construction/weather', icon: null },
      { title: 'Site Warehouse Inventory', path: '/construction/inventory', icon: null },
    ],
  },
  {
    title: 'Task Management',
    icon: 'pi pi-check-square',
    children: [
      { title: 'Kanban Board', path: '/tasks/kanban', icon: null },
      { title: 'My Tasks', path: '/tasks/my-tasks', icon: null },
      { title: 'Team Tasks', path: '/tasks/team', icon: null },
      { title: 'Task Categories', path: '/tasks/categories', icon: null },
      { title: 'Deadline Tracker', path: '/tasks/deadline', icon: null },
    ],
  },
  {
    title: 'Support & Maintenance',
    icon: 'pi pi-wrench',
    children: [
      { title: 'Asset Management', path: '/support/asset', icon: null },
      { title: 'Document Management (DMS)', path: '/support/document', icon: null },
      { title: 'Compliance & Audit', path: '/support/compliance', icon: null },
      { title: 'Risk Management (GRC)', path: '/support/risk-management', icon: null },
      { title: 'Business Intelligence (BI)', path: '/support/bi', icon: null },
      { title: 'Sustainability (ESG)', path: '/support/sustainability', icon: null },
    ],
  },
  {
    title: 'Settings & Tools',
    icon: 'pi pi-cog',
    children: [
      { title: 'System Configuration', path: '/settings/system', icon: null },
      { title: 'Modules & Feature Flags', path: '/settings/modules', icon: null },
      { title: 'Document Numbering Series', path: '/settings/numbering', icon: null },
      { title: 'Notification Templates', path: '/settings/notifications', icon: null },
      { title: 'Integration (API)', path: '/settings/integration', icon: null },
      { title: 'Data Management', path: '/settings/data', icon: null },
      { title: 'Print Format Designer', path: '/settings/print-format', icon: null },
      { title: 'Help & Support', path: '/settings/help', icon: null },
    ],
  },
];
